version: "3.8"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    container_name: postgres_db

  # Django Application
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      
  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A fampay worker -l DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - redis
      - app